
# ===================================
# map column names to be more uniform
# ===================================

column_mappings <- function(df) {
  
  colnames(df)[colnames(df) == 'Id'] <- 'id'
  colnames(df)[colnames(df) == 'MSSubClass'] <- 'sub_class'
  colnames(df)[colnames(df) == 'MSZoning'] <- 'zoning'
  colnames(df)[colnames(df) == 'LotFrontage'] <- 'lot_frontage'
  colnames(df)[colnames(df) == 'LotArea'] <- 'lot_area'
  colnames(df)[colnames(df) == 'Street'] <- 'street'
  colnames(df)[colnames(df) == 'Alley'] <- 'alley'
  colnames(df)[colnames(df) == 'LotShape'] <- 'lot_shape'
  colnames(df)[colnames(df) == 'LandContour'] <- 'land_contour'
  colnames(df)[colnames(df) == 'Utilities'] <- 'utilities'
  colnames(df)[colnames(df) == 'LotConfig'] <- 'lot_config'
  colnames(df)[colnames(df) == 'LandSlope'] <- 'land_slope'
  colnames(df)[colnames(df) == 'Neighborhood'] <- 'neighbourhood'
  colnames(df)[colnames(df) == 'Condition1'] <- 'condition_1'
  colnames(df)[colnames(df) == 'Condition2'] <- 'condition_2'
  colnames(df)[colnames(df) == 'BldgType'] <- 'dwelling_type'
  colnames(df)[colnames(df) == 'HouseStyle'] <- 'house_style'
  colnames(df)[colnames(df) == 'OverallQual'] <- 'overall_quality'
  colnames(df)[colnames(df) == 'OverallCond'] <- 'overall_condition'
  colnames(df)[colnames(df) == 'YearBuilt'] <- 'year_built'
  colnames(df)[colnames(df) == 'YearRemodAdd'] <- 'year_remodelling'
  colnames(df)[colnames(df) == 'RoofStyle'] <- 'roof_style'
  colnames(df)[colnames(df) == 'RoofMatl'] <- 'roof_material'
  colnames(df)[colnames(df) == 'Exterior1st'] <- 'ext_covering_1'
  colnames(df)[colnames(df) == 'Exterior2nd'] <- 'ext_covering_2'
  colnames(df)[colnames(df) == 'MasVnrType'] <- 'masonry_veneer_type'
  colnames(df)[colnames(df) == 'MasVnrArea'] <- 'masonry_veneer_area'
  colnames(df)[colnames(df) == 'ExterQual'] <- 'ext_quality'
  colnames(df)[colnames(df) == 'ExterCond'] <- 'ext_condition'
  colnames(df)[colnames(df) == 'Foundation'] <- 'foundation'
  colnames(df)[colnames(df) == 'BsmtQual'] <- 'basement_quality'
  colnames(df)[colnames(df) == 'BsmtCond'] <- 'basement_condition'
  colnames(df)[colnames(df) == 'BsmtExposure'] <- 'basement_exposure'
  colnames(df)[colnames(df) == 'BsmtFinType1'] <- 'basement_rating_1'
  colnames(df)[colnames(df) == 'BsmtFinSF1'] <- 'basement_area_1'
  colnames(df)[colnames(df) == 'BsmtFinType2'] <- 'basement_rating_2'
  colnames(df)[colnames(df) == 'BsmtFinSF2'] <- 'basement_area_2'
  colnames(df)[colnames(df) == 'BsmtUnfSF'] <- 'basement_area_unfinished'
  colnames(df)[colnames(df) == 'TotalBsmtSF'] <- 'basement_area_total'
  colnames(df)[colnames(df) == 'Heating'] <- 'heating'
  colnames(df)[colnames(df) == 'HeatingQC'] <- 'heating_quality'
  colnames(df)[colnames(df) == 'CentralAir'] <- 'central_air'
  colnames(df)[colnames(df) == 'Electrical'] <- 'electrical'
  colnames(df)[colnames(df) == 'X1stFlrSF'] <- '1st_floor_area'
  colnames(df)[colnames(df) == 'X2ndFlrSF'] <- '2nd_floor_area'
  colnames(df)[colnames(df) == 'LowQualFinSF'] <- 'low_quality_finished_area'
  colnames(df)[colnames(df) == 'GrLivArea'] <- 'ground_living_area'
  colnames(df)[colnames(df) == 'BsmtFullBath'] <- 'basement_full_bath'
  colnames(df)[colnames(df) == 'BsmtHalfBath'] <- 'basement_half_bath'
  colnames(df)[colnames(df) == 'FullBath'] <- 'full_bath'
  colnames(df)[colnames(df) == 'HalfBath'] <- 'half_bath'
  colnames(df)[colnames(df) == 'BedroomAbvGr'] <- 'bedroom'
  colnames(df)[colnames(df) == 'KitchenAbvGr'] <- 'kitchen'
  colnames(df)[colnames(df) == 'KitchenQual'] <- 'kitchen_quality'
  colnames(df)[colnames(df) == 'TotRmsAbvGrd'] <- 'total_rooms'
  colnames(df)[colnames(df) == 'Functional'] <- 'functionality'
  colnames(df)[colnames(df) == 'Fireplaces'] <- 'fireplaces'
  colnames(df)[colnames(df) == 'FireplaceQu'] <- 'fireplace_quality'
  colnames(df)[colnames(df) == 'GarageType'] <- 'garage_type'
  colnames(df)[colnames(df) == 'GarageYrBlt'] <- 'garage_year_built'
  colnames(df)[colnames(df) == 'GarageFinish'] <- 'garage_finish'
  colnames(df)[colnames(df) == 'GarageCars'] <- 'garage_cars'
  colnames(df)[colnames(df) == 'GarageArea'] <- 'garage_area'
  colnames(df)[colnames(df) == 'GarageQual'] <- 'garage_quality'
  colnames(df)[colnames(df) == 'GarageCond'] <- 'garage_condition'
  colnames(df)[colnames(df) == 'PavedDrive'] <- 'paved_driveway'
  colnames(df)[colnames(df) == 'WoodDeckSF'] <- 'wooden_deck_area'
  colnames(df)[colnames(df) == 'OpenPorchSF'] <- 'open_porch_area'
  colnames(df)[colnames(df) == 'EnclosedPorch'] <- 'enclosed_porch_area'
  colnames(df)[colnames(df) == 'X3SsnPorch'] <- '3season_porch_area'
  colnames(df)[colnames(df) == 'ScreenPorch'] <- 'screen_porch_area'
  colnames(df)[colnames(df) == 'PoolArea'] <- 'pool_area'
  colnames(df)[colnames(df) == 'PoolQC'] <- 'pool_quality'
  colnames(df)[colnames(df) == 'Fence'] <- 'fence_quality'
  colnames(df)[colnames(df) == 'MiscFeature'] <- 'misc_features'
  colnames(df)[colnames(df) == 'MiscVal'] <- 'misc_value'
  colnames(df)[colnames(df) == 'MoSold'] <- 'month_sold'
  colnames(df)[colnames(df) == 'YrSold'] <- 'year_sold'
  colnames(df)[colnames(df) == 'SaleType'] <- 'sale_type'
  colnames(df)[colnames(df) == 'SaleCondition'] <- 'sale_condition'
  colnames(df)[colnames(df) == 'SalePrice'] <- 'sale_price'

  return(df)
  
}
