
# ===================================
# map column names to be more uniform
# ===================================

column_mappings <- function(df) {
  
  colnames(df)[colnames(df) == 'Id'] <- 'id'
  colnames(df)[colnames(df) == 'MSSubClass'] <- 'sub_class'
  colnames(df)[colnames(df) == 'MSZoning'] <- 'zoning'
  colnames(df)[colnames(df) == 'LotFrontage'] <- 'lot_frontage'
  colnames(df)[colnames(df) == 'LotArea'] <- 'lot_area'
  colnames(df)[colnames(df) == 'Street'] <- 'street'
  colnames(df)[colnames(df) == 'Alley'] <- 'alley'
  colnames(df)[colnames(df) == 'LotShape'] <- 'lot_shape'
  colnames(df)[colnames(df) == 'LandContour'] <- 'land_contour'
  colnames(df)[colnames(df) == 'Utilities'] <- 'utilities'
  colnames(df)[colnames(df) == 'LotConfig'] <- 'lot_config'
  colnames(df)[colnames(df) == 'LandSlope'] <- 'land_slope'
  colnames(df)[colnames(df) == 'Neighborhood'] <- 'neighbourhood'
  colnames(df)[colnames(df) == 'Condition1'] <- 'condition_1'
  colnames(df)[colnames(df) == 'Condition2'] <- 'condition_2'
  colnames(df)[colnames(df) == 'BldgType'] <- 'dwelling_type'
  colnames(df)[colnames(df) == 'HouseStyle'] <- 'house_style'
  colnames(df)[colnames(df) == 'OverallQual'] <- 'overall_quality'
  colnames(df)[colnames(df) == 'OverallCond'] <- 'overall_condition'
  colnames(df)[colnames(df) == 'YearBuilt'] <- 'year_built'
  colnames(df)[colnames(df) == 'YearRemodAdd'] <- 'year_remodelling'
  colnames(df)[colnames(df) == 'RoofStyle'] <- 'roof_style'
  colnames(df)[colnames(df) == 'RoofMatl'] <- 'roof_material'
  colnames(df)[colnames(df) == 'Exterior1st'] <- 'ext_covering_1'
  colnames(df)[colnames(df) == 'Exterior2nd'] <- 'ext_covering_2'
  colnames(df)[colnames(df) == 'MasVnrType'] <- 'masonry_veneer_type'
  colnames(df)[colnames(df) == 'MasVnrArea'] <- 'masonry_veneer_area'
  colnames(df)[colnames(df) == 'ExterQual'] <- 'ext_quality'
  colnames(df)[colnames(df) == 'ExterCond'] <- 'ext_condition'
  colnames(df)[colnames(df) == 'Foundation'] <- 'foundation'
  colnames(df)[colnames(df) == 'BsmtQual'] <- 'basement_quality'
  colnames(df)[colnames(df) == 'BsmtCond'] <- 'basement_condition'
  colnames(df)[colnames(df) == 'BsmtExposure'] <- 'basement_exposure'
  colnames(df)[colnames(df) == 'BsmtFinType1'] <- 'ticket'
  colnames(df)[colnames(df) == 'BsmtFinSF1'] <- 'ticket'
  colnames(df)[colnames(df) == 'BsmtFinType2'] <- 'ticket'
  colnames(df)[colnames(df) == 'BsmtFinSF2'] <- 'ticket'
  colnames(df)[colnames(df) == 'BsmtUnfSF'] <- 'ticket'
  colnames(df)[colnames(df) == 'TotalBsmtSF'] <- 'ticket'
  colnames(df)[colnames(df) == 'Heating'] <- 'ticket'
  colnames(df)[colnames(df) == 'HeatingQC'] <- 'ticket'
  colnames(df)[colnames(df) == 'CentralAir'] <- 'ticket'
  colnames(df)[colnames(df) == 'Electrical'] <- 'ticket'
  colnames(df)[colnames(df) == '1stFlrSF'] <- 'ticket'
  colnames(df)[colnames(df) == '2ndFlrSF'] <- 'ticket'
  colnames(df)[colnames(df) == 'LowQualFinSF'] <- 'ticket'
  colnames(df)[colnames(df) == 'GrLivArea'] <- 'ticket'
  colnames(df)[colnames(df) == 'BsmtFullBath'] <- 'ticket'
  colnames(df)[colnames(df) == 'BsmtHalfBath'] <- 'ticket'
  colnames(df)[colnames(df) == 'FullBath'] <- 'ticket'
  colnames(df)[colnames(df) == 'HalfBath'] <- 'ticket'
  colnames(df)[colnames(df) == 'BedroomAbvGr'] <- 'ticket'
  colnames(df)[colnames(df) == 'KitchenAbvGr'] <- 'ticket'
  colnames(df)[colnames(df) == 'KitchenQual'] <- 'ticket'
  colnames(df)[colnames(df) == 'TotRmsAbvGrd'] <- 'ticket'
  colnames(df)[colnames(df) == 'Functional'] <- 'ticket'
  colnames(df)[colnames(df) == 'Fireplaces'] <- 'ticket'
  colnames(df)[colnames(df) == 'FireplaceQu'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageType'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageYrBlt'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageFinish'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageCars'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageArea'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageQual'] <- 'ticket'
  colnames(df)[colnames(df) == 'GarageCond'] <- 'ticket'
  colnames(df)[colnames(df) == 'PavedDrive'] <- 'ticket'
  colnames(df)[colnames(df) == 'WoodDeckSF'] <- 'ticket'
  colnames(df)[colnames(df) == 'OpenPorchSF'] <- 'ticket'
  colnames(df)[colnames(df) == 'EnclosedPorch'] <- 'ticket'
  colnames(df)[colnames(df) == '3SsnPorch'] <- 'ticket'
  colnames(df)[colnames(df) == 'ScreenPorch'] <- 'ticket'
  colnames(df)[colnames(df) == 'PoolArea'] <- 'ticket'
  colnames(df)[colnames(df) == 'PoolQC'] <- 'ticket'
  colnames(df)[colnames(df) == 'Fence'] <- 'ticket'
  colnames(df)[colnames(df) == 'MiscFeature'] <- 'ticket'
  colnames(df)[colnames(df) == 'MiscVal'] <- 'ticket'
  colnames(df)[colnames(df) == 'MoSold'] <- 'ticket'
  colnames(df)[colnames(df) == 'YrSold'] <- 'ticket'
  colnames(df)[colnames(df) == 'SaleType'] <- 'ticket'
  colnames(df)[colnames(df) == 'SaleCondition'] <- 'ticket'
  colnames(df)[colnames(df) == 'SalePrice'] <- 'ticket'

  return(df)
  
}
